### ISSUE TITLE
Don't work properly with Cemu

### ISSUE THREAD

**Issue by upperthecase** [marcowindt/WiiMoteDSU#16]
For some reason this software don't works well with Cemu. Tested in Cemu 1.25.5b. I can even put some buttons with a little patience, but most of the time the buttons don't work. Tested with Cemu's own method of input DSUClient.

**Comment by quangmng** [comment]
I gotta second with that as well. Not sure why but when connected to 5Ghz wifi network, the "buttons" are unresponsive. Not happening with 2.4Ghz tho. Also, I have to manually switch to Wiimote & Wii U gamepad input option in between navigation which is inconvenient... Tested on latest Cemu (1.25.6) with Just Dance 2019.

**Comment by marcowindt** [comment]
Closing in favor of #68.
