### ISSUE TITLE
[android] "IP address" field is never filled up.

### ISSUE THREAD

**Issue by marcowindt** [marcowindt/WiiMoteDSU#2]
Hi, I'm having similar issues and my problem is that "IP address" field is never filled up.

For building the app, I followed the README (so I don't know if there is a special installation notes) and made a github ci for it on my fork. I'm using android 10 (api level 29), idk if that changes anything or not.

_Originally posted by @fbarda in https://github.com/marcowindt/WiiMoteDSU/issues/1#issuecomment-702896118_

**Comment by marcowindt** [comment]
I saw that the permission tag for internet access was missing in the android/app/src/main/AndroidManifest.xml and [added it](https://github.com/marcowindt/WiiMoteDSU/commit/616e1251bf1706e22ea16ab3cce0eee952b436e6).

Not sure if this will solve the problem for you, but it did for me using the Android emulator.
Currently I don't have an Android device to test it with.

**Comment by Abrifq** [comment]
Let me pull and see

**Comment by Abrifq** [comment]
Yep, that fixed it.
