### ISSUE TITLE
Please consider supporting DS4 gyro on macOS

### ISSUE THREAD

**Issue by pleasejustgo** [marcowindt/WiiMoteDSU#3]
Hi, just came across this. I know this is designed to use a phone's gyro but I haven't been able to find anything on how to setup a DSU server or use a DS4 with Dolphin in any way on macOS. All guides and software is for windows. Please consider supporting DS4 gyro on macOS. Thanks.

**Comment by marcowindt** [comment]
It still crashes too often and only supports one controller at the time, but a rudimentary project can be found at [https://github.com/marcowindt/ds4macos](https://github.com/marcowindt/ds4macos).

**Comment by pleasejustgo** [comment]
Thanks so much! You're a hero. Yours might be the first DSU server for DS4 for mac!
