### ISSUE TITLE
Can i use it with an actual Wii console ?

### ISSUE THREAD

**Issue by Parinjoy** [marcowindt/WiiMoteDSU#48]
Can i use the android application with an actual wii console, if so then please make a guide of the steps to be followed.

**Comment by marcowindt** [comment]
Nope, the app works by using [cemuhook-protocol](https://v1993.github.io/cemuhook-protocol/) which utilises UDP. Actual wii remotes use bluetooth to connect with a wii console.

**Comment by Parinjoy** [comment]
Do you know any app on github or f droid or play store which allows using the phone as wiimote ?
