### ISSUE TITLE
About the Build & Run

### ISSUE THREAD

**Issue by Weichenleeeee123** [marcowindt/WiiMoteDSU#53]
I followed this procedure, but

How should I connect my iPhone to my computer when I go to step 2? I have tried to connect them with a data cable and put them under the same WiFi, but when I run the _flutter devices_, my mobile phone device is not displayed

In the third step, you said "_run inside project directory_". How do you do this specifically?

**Comment by marcowindt** [comment]
>In the third step, you said "run inside project directory". How do you do this specifically?

Go to project folder (`git clone https://github.com/marcowindt/WiiMoteDSU.git && cd WiiMoteDSU`) in a terminal and run `flutter run`

If `flutter devices` isn't returning anything (which you can run from any place) then your phone isn't properly connected. Make sure your phone has your computer as a "Trusted device", you should get a popup on your phone when you connect via USB.
