### ISSUE TITLE
Actual Wii Remote with Bluetooth

### ISSUE THREAD

**Issue by Parinjoy** [marcowindt/WiiMoteDSU#56]
Do you know any app on github or f droid or play store which allows using the phone as wiimote ? Or any other way to mimic the Bluetooth protocol for the Wii console ?

**Comment by marcowindt** [comment]
I don't know of any, most of the apps out there that I know of are more focused on connecting a wii remote to a phone. I think you need low level access to the phone's bluetooth stack to get this to work in any way. Have you asked around on other places? I guess your best shot would be to ask on some subreddit.
