### ISSUE TITLE
Add support for Cemu if possible

### ISSUE THREAD

**Issue by somefnfplayerlol** [marcowindt/WiiMoteDSU#68]

**Comment by thondorigithub1** [comment]
would love that idea.

**Comment by NomeJaExiste** [comment]
It kinda works with cemu, try cemu 2.0

**Comment by marcowindt** [comment]
I've created a [pre-release version](https://github.com/marcowindt/WiiMoteDSU/releases/tag/v0.3.0-develop.1) which should make this app work with Cemu 2.0 (not tested any other versions).

Please try it out and report back any issues.

**Comment by thondorigithub1** [comment]
motion included?

**Comment by marcowindt** [comment]
[New pre-release version](https://github.com/marcowindt/WiiMoteDSU/releases/tag/v0.3.0-develop.2) should work with cemu 2.0. Motion included, although I've only tested it with Splatoon and running WiiMoteDSU on iOS.

**Comment by marcowindt** [comment]
Cemu support is added in [v0.3.0](https://github.com/marcowindt/WiiMoteDSU/releases/tag/v0.3.0). Feel free to open a new issue when you encounter problems.
