### ISSUE TITLE
Only one dsu connect is active

### ISSUE THREAD

**Issue by NicoOrz** [marcowindt/WiiMoteDSU#86]
Using two iphone for wii gaming,however there is always only one avail in the Dolphin.When both connected,it will work for only 1-2mins,and then randomly drop a DSU server and dolphin show it is "disconnected".Re-start the app will work but only for 2min and loop again.

**Comment by marcowindt** [comment]
This issue is fixed in [v0.4.1](https://github.com/marcowindt/WiiMoteDSU/releases/tag/v0.4.1). However, this won't fix #52.
