### ISSUE TITLE
[bug]Missing '1' and '2' on normal size screen

### ISSUE THREAD

**Issue by zxhzxhz** [marcowindt/WiiMoteDSU#9]
iphone se 1st gen will not show these two buttons on screen
![8FC915BD-AB51-492C-AEC9-77BB40A160A8.png](https://i.loli.net/2021/04/10/k82UdnhuqBf56ZR.png)

**Comment by marcowindt** [comment]
Button sizes now scale to fit the screen size (v0.1.2). Thanks for opening this issue!

![Screenshot iPhone SE](https://user-images.githubusercontent.com/9336858/115156296-dc2c9000-a083-11eb-9d65-321986f52447.png)
![Screenshot iPhone 12 Pro Max](https://user-images.githubusercontent.com/9336858/115156297-dd5dbd00-a083-11eb-9ac1-1f3c939f5636.png)
