### ISSUE TITLE
Rumble support... if possible.

### ISSUE THREAD

**Issue by unauthparadox** [marcowindt/WiiMoteDSU#90]
If possible, can you add rumble support for Wii games?

**Comment by marcowindt** [comment]
That would definitely be a cool feature but unfortunately that is not possible 😞. Currently the DSU/cemu-hook protocol specification doesn't have this. Basically WiiMoteDSU is consistently sending input (buttons/motion) data to Dolphin. For it to work Dolphin (or any DSU client) should send back rumble information. The only data Dolphin sends are requests for data.
