### ISSUE TITLE
d-pad wont move 2 directions at the same time

### ISSUE THREAD

**Issue by thondorigithub1** [marcowindt/WiiMoteDSU#91]
basically, i want the dpad to move like how you can press w+d at the same time but in the d-pad since if i play wii party, it only allows me to press up on the d-pad but not up+left on the d-pad

**Comment by marcowindt** [comment]
I've added this functionality in [v0.5.0](https://github.com/marcowindt/WiiMoteDSU/releases/tag/v0.5.0). Let me know what you think 👍. Feel free to re-open this issue or create a new issue if you experience problems with it.

![image](https://user-images.githubusercontent.com/9336858/235370750-eb6359dd-ab41-4b86-b788-57f5fb877574.png)
